# Generated by Django 4.2.7 on 2023-12-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
