# Generated by Django 4.2.7 on 2023-12-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update',
            field=models.TextField(blank=True, null=True),
        ),
    ]
