# Generated by Django 4.2.7 on 2023-12-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_status_remove_task_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
