# Generated by Django 4.2.7 on 2023-12-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update',
            field=models.TextField(blank=True, null=True),
        ),
    ]
