# Generated by Django 4.2.7 on 2023-12-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_task_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='update',
        ),
    ]
