# Generated by Django 4.2.7 on 2023-12-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_task_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='wing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
