# Generated by Django 4.2.7 on 2023-12-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_task_species_alter_task_wing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='wing',
        ),
        migrations.AddField(
            model_name='task',
            name='wingspan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
