# Generated by Django 4.2.7 on 2023-12-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_task_wing_task_wingspan_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='injured',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
